[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dev-template"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
repository = "https://github.com/valory-xyz/dev-template"
keywords = ["autonomy", "autonomous", "autonolas", "service", "multi", "agent"]
classifiers = [
    "Environment :: Console",
    "Environment :: Web Environment",
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.10",
    "Topic :: Communications",
    "Topic :: Internet",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: System"
]

[[tool.poetry.packages]]
include = "packages"

[tool.poetry.dependencies]
python = "^3.10"
asn1crypto = "==1.5.1"
grpcio = "==1.56.0"
faiss-cpu = "==1.7.4"
hypothesis = "==6.21.6"
openai = "==0.27.8"
open-aea-ledger-ethereum = "==1.37.0"
openapi-spec-validator = "==0.2.8"
open-autonomy = "==0.10.10.post1"
pydantic = "==1.10.11"
py-ecc = "==5.2.0"
py-eth-sig-utils = "==0.4.0"
python-multipart = "==0.0.6"
pytz = "==2022.2.1"
toml = "^0.10.2"
openapi-core = "0.13.8"
numpy = "1.25.2"

[tool.poetry.group.dev.dependencies.tomte]
version = "==0.2.12"
extras = ["cli", "tests"]