name: chat_completion_local
author: algovera
version: 0.1.0
description: This is a chat_completion service.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: algovera/chat_completion_agent:0.1.0:bafybeic5yrxvavfxkrxabgzdwa4oyh2tzuech4zy7fdfjbz2d5rvclvuj4
number_of_agents: 1
deployment:
  agent:
    ports:
      0:
        8000: 8000
